### ISSUE TITLE
What sites to scrape from?

### ISSUE THREAD

**Issue by yowmamasita** [MojoJolo/halalan2016_scraper#1]
Also, may specific vectors ba tayo? (a specific category, tag, etc)

**Comment by MojoJolo** [comment]
@yowmamasita GMA, Manila Bulletin, etc... May alam ka pa bang iba? Iscrape ko ngayon yung Inquirer, si @marven na dun sa ABS CBN.

Basta yung mga kailangan lang natin is yung nasa items.py. Yun lang naman ata.
